# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parte', models.CharField(max_length=10)),
                ('presupuesto', models.CharField(max_length=255)),
                ('fijo', models.DecimalField(decimal_places=0, max_digits=1)),
                ('numero_cliente', models.DecimalField(decimal_places=0, max_digits=5)),
                ('nombre_cliente', models.CharField(max_length=255)),
                ('descripcion_cliente', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=255)),
                ('margen', models.DecimalField(decimal_places=2, max_digits=2)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
