# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='descripcion_cliente',
            new_name='apellido1',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nombre_cliente',
            new_name='apellido2',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='presupuesto',
            new_name='codigoImprenta',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='numero_cliente',
            new_name='cp',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fijo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='image',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='margen',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='numero_parte',
        ),
        migrations.AddField(
            model_name='producto',
            name='direcc',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='movil',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='nombreCompleto',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='pedido',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='poblacion',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='provincia',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='remesa',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='telefono',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='isbn',
            field=models.DecimalField(decimal_places=0, max_digits=13),
        ),
    ]
